### PR TITLE
Safe PEP8

### PR DESCRIPTION
**Pull request by persianpros**
Applied before on https://github.com/openembedded/meta-openembedded

### CODE REVIEW

**Comment by kraj** [comment]
these are important fixes, can you send them via email to openembedded-core@lists.openembedded.org

**Comment by persianpros** [comment]
@kraj 

Would you please do that yourself? I'm not familiar with old methods I only send PRs via github ...

**Comment by akuster** [comment]
If I forward these on to the mailing list, are you open to answering questions that may arise during review?

**Comment by persianpros** [comment]
@akuster 

Yes sure, I did this on more than 100 repos and we do it online on https://github.com/OpenVisionE2 repos via github actions.

**Comment by akuster** [comment]
patches sent to mailing list.

**Comment by persianpros** [comment]
@akuster 

Would you please do that for https://github.com/openembedded/bitbake/pull/31 too?

**Pull request closed without merging**
